name: 'Upload a Build Artifact'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
  
  steps:
    - uses: actions/upload-artifact@v3
      with:
      name: my-artifact
      paht: path/to/artifact/
